---
# Ansible Playbook: Automated SSH Key Rotation
# Purpose: Batch update SSH keys for specific users across multiple instances
# Variables are defined in inventory.ini file
# 
# Operation Modes:
#   deploy  - Deploy new SSH key (default)
#   verify  - Verify new key is deployed
#   cleanup - Remove old SSH key
#
# Usage:
#   ansible-playbook ansible-update-ssh-key.yml -i inventory.ini -e "operation_mode=deploy"
#   ansible-playbook ansible-update-ssh-key.yml -i inventory.ini -e "operation_mode=verify"
#   ansible-playbook ansible-update-ssh-key.yml -i inventory.ini -e "operation_mode=cleanup"

- name: SSH Key Management for EC2 Instances
  hosts: all
  become: yes
  
  tasks:
    # ============================================
    # Common Tasks
    # ============================================
    - name: Get current date for backup suffix
      set_fact:
        backup_date: "{{ ansible_date_time.date | replace('-', '') }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"
    # ============================================
    # Common Tasks
    # ============================================
    - name: Validate required variables
      fail:
        msg: "new_private_key_path variable is not set."
      when: new_private_key_path == ""

    - name: Check if user exists
      getent:
        database: passwd
        key: "{{ target_user }}"
      register: user_check
      failed_when: false

    - name: Fail if user does not exist
      fail:
        msg: "User {{ target_user }} does not exist."
      when: user_check.ansible_facts.getent_passwd is not defined

    - name: Get user home directory
      set_fact:
        user_home: "{{ user_check.ansible_facts.getent_passwd[target_user][4] }}"

    # ============================================
    # Mode 1: Deploy New Key
    # ============================================
    - name: "[DEPLOY] Copy new private key to temp location"
      copy:
        src: "{{ new_private_key_path }}"
        dest: "/tmp/new_key.pem"
        mode: '0600'
      when: operation_mode == "deploy"
      no_log: true

    - name: "[DEPLOY] Extract public key from new private key"
      shell: ssh-keygen -y -f /tmp/new_key.pem
      register: new_public_key
      when: operation_mode == "deploy"
      no_log: true

    - name: "[DEPLOY] Check if new key already exists in authorized_keys"
      shell: grep -qF "{{ new_public_key.stdout }}" {{ user_home }}/.ssh/authorized_keys
      register: new_key_exists
      failed_when: false
      changed_when: false
      when: operation_mode == "deploy"
      no_log: true

    - name: "[DEPLOY] Skip if already deployed"
      debug:
        msg: "SSH key has already been deployed. Skipping."
      when: 
        - operation_mode == "deploy"
        - new_key_exists.rc == 0

    - name: "[DEPLOY] Backup existing authorized_keys"
      copy:
        src: "{{ user_home }}/.ssh/authorized_keys"
        dest: "{{ user_home }}/.ssh/authorized_keys.backup.{{ backup_date }}"
        remote_src: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'
      when: 
        - operation_mode == "deploy"
        - new_key_exists.rc != 0

    - name: "[DEPLOY] Add new public key to authorized_keys"
      lineinfile:
        path: "{{ user_home }}/.ssh/authorized_keys"
        line: "{{ new_public_key.stdout }}"
        create: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'
      when: 
        - operation_mode == "deploy"
        - new_key_exists.rc != 0
      no_log: true

    - name: "[DEPLOY] Remove temporary private key"
      file:
        path: /tmp/new_key.pem
        state: absent
      when: operation_mode == "deploy"

    - name: "[DEPLOY] Display completion message"
      debug:
        msg: "✓ New SSH key has been successfully deployed for user {{ target_user }}"
      when: 
        - operation_mode == "deploy"
        - new_key_exists.rc != 0

    # ============================================
    # Mode 2: Verify New Key
    # ============================================
    - name: "[VERIFY] Copy new private key to temp location"
      copy:
        src: "{{ new_private_key_path }}"
        dest: "/tmp/verify_key.pem"
        mode: '0600'
      when: operation_mode == "verify"
      no_log: true

    - name: "[VERIFY] Extract public key from new private key"
      shell: ssh-keygen -y -f /tmp/verify_key.pem
      register: verify_public_key
      when: operation_mode == "verify"
      no_log: true

    - name: "[VERIFY] Read authorized_keys content"
      slurp:
        src: "{{ user_home }}/.ssh/authorized_keys"
      register: authorized_keys_content
      when: operation_mode == "verify"
      no_log: true

    - name: "[VERIFY] Check if new key exists in authorized_keys"
      set_fact:
        new_key_exists: "{{ verify_public_key.stdout in (authorized_keys_content.content | b64decode) }}"
      when: operation_mode == "verify"

    - name: "[VERIFY] Display verification result - SUCCESS"
      debug:
        msg: "✓ VERIFIED: New SSH key is present in authorized_keys for user {{ target_user }}"
      when: 
        - operation_mode == "verify"
        - new_key_exists | bool

    - name: "[VERIFY] Display verification result - FAILED"
      debug:
        msg: "✗ FAILED: New SSH key is NOT found in authorized_keys for user {{ target_user }}"
      when: 
        - operation_mode == "verify"
        - not (new_key_exists | bool)

    - name: "[VERIFY] Fail if new key not found"
      fail:
        msg: "New SSH key verification failed. Key not found in authorized_keys."
      when: 
        - operation_mode == "verify"
        - not (new_key_exists | bool)

    - name: "[VERIFY] Remove temporary private key"
      file:
        path: /tmp/verify_key.pem
        state: absent
      when: operation_mode == "verify"

    # ============================================
    # Mode 3: Cleanup Old Key
    # ============================================
    - name: "[CLEANUP] Copy old private key to temp location"
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: "/tmp/old_key.pem"
        mode: '0600'
      when: operation_mode == "cleanup"
      no_log: true

    - name: "[CLEANUP] Extract public key from old private key"
      shell: ssh-keygen -y -f /tmp/old_key.pem
      register: old_public_key
      when: operation_mode == "cleanup"
      no_log: true

    - name: "[CLEANUP] Check if old key exists in authorized_keys"
      shell: grep -qF "{{ old_public_key.stdout }}" {{ user_home }}/.ssh/authorized_keys
      register: old_key_check
      failed_when: false
      changed_when: false
      when: operation_mode == "cleanup"
      no_log: true

    - name: "[CLEANUP] Display if old key not found"
      debug:
        msg: "ℹ Old SSH key was not found in authorized_keys for user {{ target_user }}"
      when: 
        - operation_mode == "cleanup"
        - old_key_check.rc != 0

    - name: "[CLEANUP] Backup authorized_keys before cleanup"
      copy:
        src: "{{ user_home }}/.ssh/authorized_keys"
        dest: "{{ user_home }}/.ssh/authorized_keys.backup.cleanup_{{ backup_date }}"
        remote_src: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'
      when: 
        - operation_mode == "cleanup"
        - old_key_check.rc == 0

    - name: "[CLEANUP] Remove old public key from authorized_keys"
      shell: |
        grep -vF "{{ old_public_key.stdout }}" {{ user_home }}/.ssh/authorized_keys > {{ user_home }}/.ssh/authorized_keys.tmp
        mv {{ user_home }}/.ssh/authorized_keys.tmp {{ user_home }}/.ssh/authorized_keys
        chown {{ target_user }}:{{ target_user }} {{ user_home }}/.ssh/authorized_keys
        chmod 600 {{ user_home }}/.ssh/authorized_keys
      when: 
        - operation_mode == "cleanup"
        - old_key_check.rc == 0
      no_log: true

    - name: "[CLEANUP] Verify old key removal"
      shell: grep -qF "{{ old_public_key.stdout }}" {{ user_home }}/.ssh/authorized_keys
      register: verify_removal
      failed_when: false
      changed_when: false
      when: 
        - operation_mode == "cleanup"
        - old_key_check.rc == 0
      no_log: true

    - name: "[CLEANUP] Display cleanup result - SUCCESS"
      debug:
        msg: "✓ Old SSH key has been removed from authorized_keys for user {{ target_user }}"
      when: 
        - operation_mode == "cleanup"
        - old_key_check.rc == 0
        - verify_removal.rc != 0

    - name: "[CLEANUP] Display cleanup result - FAILED"
      debug:
        msg: "⚠ Warning: Old SSH key removal may have failed. Please verify manually."
      when: 
        - operation_mode == "cleanup"
        - old_key_check.rc == 0
        - verify_removal.rc == 0

    - name: "[CLEANUP] Remove temporary private key"
      file:
        path: /tmp/old_key.pem
        state: absent
      when: operation_mode == "cleanup"
